---
- name: configure_zabbix_server | configuring zabbix server
  template:
    src: "etc/zabbix/zabbix_server.conf.j2"
    dest: "/etc/zabbix/zabbix_server.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zabbix-server
