---
- name: manage_mysql_db | ensuring db exists
  mysql_db:
    name: "{{ zabbix_db_info['name'] }}"
    state: "present"
  become: true

- name: manage_mysql_db | setting permissions on db
  mysql_user:
    name: "{{ zabbix_db_info['user'] }}"
    password: "{{ zabbix_db_info['password'] }}"
    priv: "{{ zabbix_db_info['name'] }}.*:ALL"
  become: true

- name: manage_mysql_db | checking if db already imported
  stat:
    path: "/var/log/.db_imported"
  register: _zabbix_db_imported_check

# Below is currently the only method I could consistently get to work. The
# Ansible module for mysql to import the db from archive results in errors.
# https://github.com/ansible/ansible/issues/20196
- name: manage_mysql_db | Importing DB Schema
  shell: >
         zcat {{ zabbix_mysql_schema_archive }} | mysql -u{{ zabbix_db_info['user'] }}
         -p{{ zabbix_db_info['password'] }} {{ zabbix_db_info['name'] }}
  become: true
  register: "_zabbix_db_imported"
  when: not _zabbix_db_imported_check['stat']['exists']

- name: manage_mysql_db | marking db as imported
  file:
    path: "/var/log/.db_imported"
    state: "touch"
  become: true
  when: _zabbix_db_imported['changed']
