---
# handlers file for ansible-zabbix
- name: restart apache2
  service:
    name: "apache2"
    state: "restarted"
    enabled: true
  become: true

- name: restart zabbix-server
  service:
    name: "zabbix-server"
    state: "restarted"
    enabled: true
  become: true
