---
# handlers file for ansible-zabbix
- name: restart apache2
  service:
    name: "apache2"
    state: restarted

- name: restart zabbix-agent
  service:
    name: "zabbix-agent"
    state: restarted
        
- name: restart zabbix-server
  service:
    name: "zabbix-server"
    state: restarted
